package main

import (
	"fmt"
	"os"
	"strings"
	"time"

	"recac/internal/notify"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	digestSince  time.Duration
	digestOutput string
	digestSlack  bool
)

var digestCmd = &cobra.Command{
	Use:   "digest",
	Short: "Generate a daily project digest and status report",
	Long: `Generates a comprehensive summary of project activity, including:
- Recent Git commits
- Completed agent sessions
- Current code health (audit score)

The report is generated by an AI agent to provide a natural language briefing.
Can optionally send the report to Slack.`,
	RunE: runDigest,
}

func init() {
	rootCmd.AddCommand(digestCmd)
	digestCmd.Flags().DurationVar(&digestSince, "since", 24*time.Hour, "Time window for the digest")
	digestCmd.Flags().StringVarP(&digestOutput, "output", "o", "", "Output file path (default stdout)")
	digestCmd.Flags().BoolVar(&digestSlack, "slack", false, "Send the digest to Slack")
}

func runDigest(cmd *cobra.Command, args []string) error {
	ctx := cmd.Context()
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get current working directory: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "📊 Generating Project Digest (Window: %s)...\n", digestSince)

	// 1. Gather Git Data
	gitClient := gitClientFactory()
	var gitLogs []string
	if gitClient.RepoExists(cwd) {
		sinceArg := fmt.Sprintf("--since=%s", time.Now().Add(-digestSince).Format("2006-01-02 15:04:05"))
		// Format: Hash - Author - Message
		logs, err := gitClient.Log(cwd, sinceArg, "--pretty=format:%h - %an - %s")
		if err == nil {
			gitLogs = logs
		} else {
			fmt.Fprintf(cmd.ErrOrStderr(), "Warning: Failed to fetch git logs: %v\n", err)
		}
	} else {
		fmt.Fprintln(cmd.ErrOrStderr(), "Warning: Not a git repository.")
	}

	// 2. Gather Session Data
	sm, err := sessionManagerFactory()
	if err != nil {
		return fmt.Errorf("failed to create session manager: %w", err)
	}

	sessions, err := sm.ListSessions()
	var recentSessions []string
	if err == nil {
		startTime := time.Now().Add(-digestSince)
		for _, s := range sessions {
			if s.StartTime.After(startTime) {
				status := s.Status
				if status == "" {
					status = "unknown"
				}
				recentSessions = append(recentSessions, fmt.Sprintf("- %s (%s): %s", s.Name, status, s.StartTime.Format(time.RFC3339)))
			}
		}
	} else {
		fmt.Fprintf(cmd.ErrOrStderr(), "Warning: Failed to list sessions: %v\n", err)
	}

	// 3. Gather Audit Data (Simplified)
	// We call runAudit from audit.go
	var auditSummary string
	auditRes, err := runAudit(cwd)
	if err == nil {
		auditSummary = fmt.Sprintf("Score: %d/100 (Complexity: %.2f, Duplication: %d blocks, TODOs: %d)",
			auditRes.Score, auditRes.Complexity.Average, auditRes.Duplication.Blocks, auditRes.Todos.Count)
	} else {
		auditSummary = fmt.Sprintf("Audit failed: %v", err)
	}

	// 4. Construct Prompt
	var promptBuilder strings.Builder
	promptBuilder.WriteString("You are a Technical Lead creating a Daily Project Digest.\n")
	promptBuilder.WriteString("Summarize the following activity into a concise, professional markdown report.\n")
	promptBuilder.WriteString("The report should have sections: 'Executive Summary', 'Key Changes', 'Agent Activity', and 'Health Check'.\n\n")

	promptBuilder.WriteString("## Git Activity (Last " + digestSince.String() + ")\n")
	if len(gitLogs) > 0 {
		for _, l := range gitLogs {
			promptBuilder.WriteString(l + "\n")
		}
	} else {
		promptBuilder.WriteString("No commits found.\n")
	}

	promptBuilder.WriteString("\n## Agent Sessions\n")
	if len(recentSessions) > 0 {
		for _, s := range recentSessions {
			promptBuilder.WriteString(s + "\n")
		}
	} else {
		promptBuilder.WriteString("No sessions run.\n")
	}

	promptBuilder.WriteString("\n## Code Health Audit\n")
	promptBuilder.WriteString(auditSummary + "\n")

	// 5. Generate with Agent
	provider := viper.GetString("provider")
	model := viper.GetString("model")
	ag, err := agentClientFactory(ctx, provider, model, cwd, "recac-digest")
	if err != nil {
		return fmt.Errorf("failed to initialize agent: %w", err)
	}

	fmt.Fprintln(cmd.OutOrStdout(), "🧠 Consulting AI agent for summary...")
	report, err := ag.Send(ctx, promptBuilder.String())
	if err != nil {
		return fmt.Errorf("agent failed to generate report: %w", err)
	}

	// Remove potential markdown code blocks if the agent wrapped the whole thing
	if strings.HasPrefix(strings.TrimSpace(report), "```markdown") {
		report = strings.TrimPrefix(strings.TrimSpace(report), "```markdown")
		report = strings.TrimSuffix(report, "```")
	}

	// 6. Output
	if digestOutput != "" {
		if err := os.WriteFile(digestOutput, []byte(report), 0644); err != nil {
			return fmt.Errorf("failed to write output file: %w", err)
		}
		fmt.Fprintf(cmd.OutOrStdout(), "✅ Digest saved to %s\n", digestOutput)
	} else {
		fmt.Fprintln(cmd.OutOrStdout(), "\n"+report+"\n")
	}

	// 7. Notify Slack
	if digestSlack {
		fmt.Fprintln(cmd.OutOrStdout(), "📨 Sending to Slack...")
		nm := notify.NewManager(func(format string, args ...interface{}) {
			// Redirect internal notify logs to debug or ignore
			// fmt.Printf(format+"\n", args...)
		})

		// We use "on_success" style or custom?
		// Manager.Notify uses hardcoded styles.
		// Let's use EventProjectComplete for a Green checkmark style, or just generic "on_start" (Blue).
		// Or we can just send the raw message if we bypassed Notify?
		// No, let's use the Notify abstraction.
		// Use EventSuccess as it is generally positive.
		_, err := nm.Notify(ctx, notify.EventSuccess, "📋 **Daily Digest**\n\n"+report, "")
		if err != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "Failed to send Slack notification: %v\n", err)
		} else {
			fmt.Fprintln(cmd.OutOrStdout(), "✅ Sent to Slack.")
		}
	}

	return nil
}
