package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateHookScript(t *testing.T) {
	tests := []struct {
		name    string
		binPath string
		profile string
		want    []string // substrings to check
	}{
		{
			name:    "default profile",
			binPath: "/usr/bin/recac",
			profile: "default",
			want: []string{
				`RECAC_BIN="/usr/bin/recac"`,
				`$RECAC_BIN security`,
				`$RECAC_BIN audit --fail --min-score 60`,
			},
		},
		{
			name:    "strict profile",
			binPath: "/opt/recac",
			profile: "strict",
			want: []string{
				`RECAC_BIN="/opt/recac"`,
				`$RECAC_BIN security --fail`,
				`$RECAC_BIN audit --fail --min-score 80`,
			},
		},
		{
			name:    "fast profile",
			binPath: "recac",
			profile: "fast",
			want: []string{
				`RECAC_BIN="recac"`,
				`$RECAC_BIN security --fail`,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := generateHookScript(tt.binPath, tt.profile)
			for _, w := range tt.want {
				if !strings.Contains(got, w) {
					t.Errorf("generateHookScript() missing %q, got:\n%s", w, got)
				}
			}
		})
	}
}

func TestHooksInstallUninstall(t *testing.T) {
	// Setup temp dir
	tmpDir := t.TempDir()
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current wd: %v", err)
	}
	defer os.Chdir(originalWd)

	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("failed to chdir: %v", err)
	}

	// Case 1: Not a git repo
	if err := hooksInstallCmd.RunE(hooksInstallCmd, nil); err == nil {
		t.Error("expected error when not a git repo, got nil")
	}

	// Create .git directory
	gitDir := filepath.Join(tmpDir, ".git")
	if err := os.Mkdir(gitDir, 0755); err != nil {
		t.Fatalf("failed to create .git: %v", err)
	}

	// Case 2: Install successfully
	if err := hooksInstallCmd.RunE(hooksInstallCmd, nil); err != nil {
		t.Errorf("install failed: %v", err)
	}

	hookPath := filepath.Join(gitDir, "hooks", "pre-commit")
	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		t.Error("pre-commit hook not created")
	}

	content, _ := os.ReadFile(hookPath)
	if !strings.Contains(string(content), "Generated by recac hooks") {
		t.Error("hook content incorrect")
	}

	// Case 3: Re-install fails without force
	if err := hooksInstallCmd.RunE(hooksInstallCmd, nil); err == nil {
		t.Error("expected error on re-install without force")
	}

	// Case 4: Force install
	hookForce = true
	defer func() { hookForce = false }()
	if err := hooksInstallCmd.RunE(hooksInstallCmd, nil); err != nil {
		t.Errorf("force install failed: %v", err)
	}

	// Case 5: Uninstall
	if err := hooksUninstallCmd.RunE(hooksUninstallCmd, nil); err != nil {
		t.Errorf("uninstall failed: %v", err)
	}

	if _, err := os.Stat(hookPath); !os.IsNotExist(err) {
		t.Error("pre-commit hook not removed")
	}

	// Case 6: Uninstall again (safe)
	if err := hooksUninstallCmd.RunE(hooksUninstallCmd, nil); err != nil {
		t.Errorf("uninstall again failed: %v", err)
	}
}
