package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"recac/internal/db"

	"github.com/spf13/cobra"
)

func newPlanVisualizeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "visualize [plan_file]",
		Short: "Visualize a feature plan as a Mermaid graph",
		Long:  `Reads a JSON feature list (generated by 'plan') and generates a Mermaid dependency graph.`,
		Args:  cobra.MaximumNArgs(1),
		RunE:  runPlanVisualize,
	}

	cmd.Flags().StringP("output", "o", "", "Output file for the Mermaid graph")
	cmd.Flags().String("format", "mermaid", "Output format (currently only mermaid supported)")

	return cmd
}

func runPlanVisualize(cmd *cobra.Command, args []string) error {
	planFile := "feature_list.json"
	if len(args) > 0 {
		planFile = args[0]
	}

	outputFile, _ := cmd.Flags().GetString("output")

	// Read Plan
	content, err := os.ReadFile(planFile)
	if err != nil {
		return fmt.Errorf("failed to read plan file %s: %w", planFile, err)
	}

	var featureList db.FeatureList
	if err := json.Unmarshal(content, &featureList); err != nil {
		return fmt.Errorf("failed to parse plan file: %w", err)
	}

	// Generate Graph
	graph := generateMermaidPlan(featureList)

	// Output
	if outputFile != "" {
		if err := os.WriteFile(outputFile, []byte(graph), 0644); err != nil {
			return fmt.Errorf("failed to write output file: %w", err)
		}
		fmt.Fprintf(cmd.OutOrStdout(), "Graph saved to %s\n", outputFile)
	} else {
		fmt.Fprintln(cmd.OutOrStdout(), graph)
	}

	return nil
}

func generateMermaidPlan(list db.FeatureList) string {
	var sb strings.Builder
	sb.WriteString("graph TD\n")
	if list.ProjectName != "" {
		sb.WriteString(fmt.Sprintf("    title %s\n", list.ProjectName))
	}

	// Sort features by ID for deterministic output
	// Copy slice to avoid modifying original if passed by ref (though it's a struct here)
	features := make([]db.Feature, len(list.Features))
	copy(features, list.Features)
	sort.Slice(features, func(i, j int) bool {
		return features[i].ID < features[j].ID
	})

	// Add Nodes
	for _, f := range features {
		safeID := sanitizePlanID(f.ID)
		// Truncate description for label
		desc := f.Description
		runes := []rune(desc)
		if len(runes) > 30 {
			desc = string(runes[:27]) + "..."
		}
		// Escape quotes
		desc = strings.ReplaceAll(desc, "\"", "'")

		// Status styling
		style := ""
		if f.Passes {
			style = ":::done"
		} else if strings.ToLower(f.Status) == "in_progress" {
			style = ":::active"
		} else {
			style = ":::pending"
		}

		sb.WriteString(fmt.Sprintf("    %s[\"%s<br/>%s\"]%s\n", safeID, f.ID, desc, style))
	}

	// Add Edges
	for _, f := range features {
		safeID := sanitizePlanID(f.ID)
		// Sort dependencies for determinism
		deps := make([]string, len(f.Dependencies.DependsOnIDs))
		copy(deps, f.Dependencies.DependsOnIDs)
		sort.Strings(deps)

		for _, dep := range deps {
			safeDep := sanitizePlanID(dep)
			sb.WriteString(fmt.Sprintf("    %s --> %s\n", safeDep, safeID))
		}
	}

	// Add Styles
	sb.WriteString("    classDef done fill:#d4edda,stroke:#28a745,color:black;\n")
	sb.WriteString("    classDef active fill:#cce5ff,stroke:#004085,color:black;\n")
	sb.WriteString("    classDef pending fill:#fff3cd,stroke:#856404,color:black;\n")

	return sb.String()
}

func sanitizePlanID(id string) string {
	return strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			return r
		}
		return '_'
	}, id)
}
