package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"recac/internal/db"

	"github.com/spf13/cobra"
)

var (
	visualizeOutput string
)

var planVisualizeCmd = &cobra.Command{
	Use:   "visualize [feature-list-json]",
	Short: "Visualize the feature plan as a Mermaid diagram",
	Long: `Reads a JSON feature list (generated by 'recac plan') and outputs a Mermaid Flowchart.
The diagram visualizes feature dependencies and statuses.`,
	Args: cobra.MaximumNArgs(1),
	RunE: runPlanVisualize,
}

func init() {
	planCmd.AddCommand(planVisualizeCmd)
	planVisualizeCmd.Flags().StringVarP(&visualizeOutput, "output", "o", "", "Output file path (default: stdout)")
}

func runPlanVisualize(cmd *cobra.Command, args []string) error {
	inputFile := "feature_list.json"
	if len(args) > 0 {
		inputFile = args[0]
	}

	// 1. Read JSON
	data, err := os.ReadFile(inputFile)
	if err != nil {
		return fmt.Errorf("failed to read feature list file %s: %w", inputFile, err)
	}

	var featureList db.FeatureList
	if err := json.Unmarshal(data, &featureList); err != nil {
		return fmt.Errorf("failed to parse JSON: %w", err)
	}

	// 2. Generate Mermaid
	mermaid := generateMermaidPlan(featureList)

	// 3. Output
	if visualizeOutput != "" {
		if err := os.WriteFile(visualizeOutput, []byte(mermaid), 0644); err != nil {
			return fmt.Errorf("failed to write output file: %w", err)
		}
		fmt.Fprintf(cmd.OutOrStdout(), "Diagram saved to %s\n", visualizeOutput)
	} else {
		fmt.Fprintln(cmd.OutOrStdout(), mermaid)
	}

	return nil
}

func generateMermaidPlan(list db.FeatureList) string {
	var sb strings.Builder
	sb.WriteString("graph TD\n")

	// Helper to clean ID for Mermaid
	idReplacer := strings.NewReplacer("-", "_", " ", "_")
	cleanID := func(id string) string {
		return idReplacer.Replace(id)
	}

	// Helper to clean Text
	cleanText := func(text string) string {
		text = strings.ReplaceAll(text, "\"", "'")
		if len(text) > 40 {
			text = text[:37] + "..."
		}
		return text
	}

	for _, f := range list.Features {
		nodeID := cleanID(f.ID)
		sb.WriteString(fmt.Sprintf("    %s[\"%s: %s\"]\n", nodeID, f.ID, cleanText(f.Description)))

		// Dependencies
		for _, dep := range f.Dependencies.DependsOnIDs {
			depID := cleanID(dep)
			// Only add edge if dep exists (optional check, but good for graph integrity)
			sb.WriteString(fmt.Sprintf("    %s --> %s\n", depID, nodeID))
		}

		// Styling
		style := ""
		status := strings.ToLower(f.Status)
		if status == "done" || status == "implemented" || f.Passes {
			style = "fill:#9f9,stroke:#333,stroke-width:2px"
		} else if status == "in_progress" || status == "wip" {
			style = "fill:#ff9,stroke:#333,stroke-width:2px"
		} else if status == "failed" {
			style = "fill:#f99,stroke:#333,stroke-width:2px"
		} else {
			// Based on priority
			p := strings.ToLower(f.Priority)
			if strings.Contains(p, "high") || strings.Contains(p, "poc") {
				style = "fill:#f9f,stroke:#333,stroke-dasharray: 5 5"
			} else if strings.Contains(p, "mvp") {
				style = "fill:#ccf,stroke:#333"
			} else {
				style = "fill:#eee,stroke:#333"
			}
		}

		if style != "" {
			sb.WriteString(fmt.Sprintf("    style %s %s\n", nodeID, style))
		}
	}

	return sb.String()
}
