package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"recac/internal/utils"
	"strings"

	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// QuizQuestion represents a single quiz question
type QuizQuestion struct {
	Question      string   `json:"question"`
	Options       []string `json:"options"`
	CorrectAnswer int      `json:"correct_answer"` // Index of the correct option (0-based)
	Explanation   string   `json:"explanation"`
}

var (
	quizAgentFactory    = agentClientFactory
	generateContextFunc = GenerateCodebaseContext
	quizQuestions       int
	quizFocus           string
)

var quizCmd = &cobra.Command{
	Use:   "quiz",
	Short: "Take an interactive quiz about the codebase",
	Long: `Starts an interactive quiz about the codebase, generated by AI.
It analyzes the repository structure and contents to generate relevant questions
to test your knowledge of the project.`,
	RunE: runQuiz,
}

func init() {
	quizCmd.Flags().IntVarP(&quizQuestions, "questions", "q", 5, "Number of questions to generate")
	quizCmd.Flags().StringVarP(&quizFocus, "focus", "f", ".", "Directory or file to focus the quiz on")
	if rootCmd != nil {
		rootCmd.AddCommand(quizCmd)
	}
}

func runQuiz(cmd *cobra.Command, args []string) error {
	fmt.Println("Generating quiz questions from codebase... this may take a moment.")

	questions, err := generateQuiz(cmd.Context())
	if err != nil {
		return fmt.Errorf("failed to generate quiz: %w", err)
	}

	if len(questions) == 0 {
		return fmt.Errorf("no questions generated")
	}

	p := tea.NewProgram(initialQuizModel(questions), tea.WithAltScreen())
	if _, err := p.Run(); err != nil {
		return fmt.Errorf("error running quiz: %w", err)
	}
	return nil
}

func generateQuiz(ctx context.Context) ([]QuizQuestion, error) {
	// Generate Context
	opts := ContextOptions{
		Roots:   []string{quizFocus},
		MaxSize: 10 * 1024, // 10KB limit per file to avoid huge prompts
		Tree:    true,
	}

	codebaseContext, err := generateContextFunc(opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate codebase context: %w", err)
	}

	// Initialize Agent
	provider := viper.GetString("agent_provider")
	if provider == "" {
		provider = os.Getenv("RECAC_AGENT_PROVIDER")
	}

	model := viper.GetString("agent_model")

	a, err := quizAgentFactory(ctx, provider, model, ".", "recac-quiz")
	if err != nil {
		return nil, fmt.Errorf("failed to init agent: %w", err)
	}

	prompt := fmt.Sprintf(`Analyze the provided codebase context. Create %d multiple-choice questions to test a developer's understanding of this code.
Return a JSON array of objects with keys: 'question', 'options' (array of strings), 'correct_answer' (integer index 0-based), and 'explanation'.
The questions should cover architecture, specific logic, or design patterns found in the code.

CONTEXT:
%s

Example JSON format:
[
  {
    "question": "What is the purpose of the 'main' package?",
    "options": ["To run the app", "To test the app", "To build the app"],
    "correct_answer": 0,
    "explanation": "The main package contains the entry point..."
  }
]
IMPORTANT: Return ONLY the JSON array. Do not include markdown code blocks.`, quizQuestions, codebaseContext)

	resp, err := a.Send(ctx, prompt)
	if err != nil {
		return nil, err
	}

	// Clean up response
	resp = utils.CleanJSONBlock(resp)

	var qs []QuizQuestion
	if err := json.Unmarshal([]byte(resp), &qs); err != nil {
		return nil, fmt.Errorf("failed to parse agent response: %w\nResponse: %s", err, resp)
	}

	return qs, nil
}

// TUI Model

type quizModel struct {
	questions      []QuizQuestion
	current        int
	score          int
	selectedOption int
	showResult     bool
	finished       bool
	viewport       viewport.Model
	ready          bool
}

func initialQuizModel(qs []QuizQuestion) quizModel {
	return quizModel{
		questions:      qs,
		current:        0,
		selectedOption: 0,
	}
}

func (m quizModel) Init() tea.Cmd {
	return nil
}

func (m quizModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "ctrl+c", "q", "esc":
			if m.finished || msg.String() == "ctrl+c" {
				return m, tea.Quit
			}
			// Allow quitting anytime if user really wants to, but 'q' is also used for quit in finished screen
			// During quiz, maybe esc/ctrl+c is better for quitting
			return m, tea.Quit
		}

		if m.finished {
			return m, tea.Quit
		}

		if m.showResult {
			// Waiting for next question
			if msg.String() == "enter" || msg.String() == " " {
				if m.current < len(m.questions)-1 {
					m.current++
					m.showResult = false
					m.selectedOption = 0
				} else {
					m.finished = true
				}
			}
			return m, nil
		}

		switch msg.String() {
		case "up", "k":
			if m.selectedOption > 0 {
				m.selectedOption--
			}
		case "down", "j":
			if m.selectedOption < len(m.questions[m.current].Options)-1 {
				m.selectedOption++
			}
		case "enter", " ":
			m.showResult = true
			if m.selectedOption == m.questions[m.current].CorrectAnswer {
				m.score++
			}
		}

	case tea.WindowSizeMsg:
		if !m.ready {
			m.viewport = viewport.New(msg.Width, msg.Height)
			m.ready = true
		} else {
			m.viewport.Width = msg.Width
			m.viewport.Height = msg.Height
		}
	}
	return m, nil
}

func (m quizModel) View() string {
	if !m.ready {
		return "Initializing..."
	}

	if m.finished {
		return m.finalScoreView()
	}

	return m.questionView()
}

func (m quizModel) finalScoreView() string {
	titleStyle := lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("205")).MarginBottom(1)
	scoreStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("220")).Bold(true)

	s := fmt.Sprintf("Quiz Complete!\n\nYour Score: %d/%d\n\n", m.score, len(m.questions))

	percentage := float64(m.score) / float64(len(m.questions)) * 100
	var msg string
	if percentage == 100 {
		msg = "Perfect score! You are a master of this codebase!"
	} else if percentage >= 80 {
		msg = "Great job! You know your stuff."
	} else if percentage >= 50 {
		msg = "Good effort. Keep exploring the code."
	} else {
		msg = "Time to read the docs a bit more."
	}

	return titleStyle.Render("Results") + "\n" + scoreStyle.Render(s) + msg + "\n\nPress q to quit."
}

func (m quizModel) questionView() string {
	q := m.questions[m.current]

	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("Question %d/%d\n\n", m.current+1, len(m.questions)))
	sb.WriteString(lipgloss.NewStyle().Bold(true).Render(q.Question) + "\n\n")

	// Options
	for i, opt := range q.Options {
		cursor := " "
		style := lipgloss.NewStyle()

		if m.showResult {
			if i == q.CorrectAnswer {
				style = style.Foreground(lipgloss.Color("42")) // Green
				if i == m.selectedOption {
					cursor = "✓"
				} else {
					cursor = " "
				}
			} else if i == m.selectedOption {
				style = style.Foreground(lipgloss.Color("196")) // Red
				cursor = "✗"
			}
		} else {
			if i == m.selectedOption {
				cursor = ">"
				style = style.Foreground(lipgloss.Color("205")) // Pink
			}
		}

		sb.WriteString(fmt.Sprintf("%s %s\n", cursor, style.Render(opt)))
	}

	// Explanation
	if m.showResult {
		sb.WriteString("\n")
		sb.WriteString(lipgloss.NewStyle().Foreground(lipgloss.Color("240")).Render("Explanation: " + q.Explanation))
		sb.WriteString("\n\nPress Enter for next question...")
	} else {
		sb.WriteString("\n\nUse ↑/↓ to select, Enter to submit.")
	}

	return sb.String()
}
