package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"strings"

	"recac/internal/utils"

	"github.com/AlecAivazis/survey/v2"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	_ "github.com/lib/pq"
	_ "modernc.org/sqlite"
)

var (
	seedTable string
	seedCount int
	seedYes   bool
)

var seedCmd = &cobra.Command{
	Use:   "seed [connection-string]",
	Short: "Seed database with realistic mock data using AI",
	Long: `Connects to a database and populates a specific table with realistic test data generated by AI.
It analyzes the table schema (columns, types, keys) to ensure data validity.`,
	Example: `  recac seed ./my.db --table users --count 10
  recac seed postgres://localhost/mydb --count 50`,
	RunE: runSeed,
}

func init() {
	rootCmd.AddCommand(seedCmd)
	seedCmd.Flags().StringVarP(&seedTable, "table", "t", "", "Table to seed")
	seedCmd.Flags().IntVarP(&seedCount, "count", "c", 10, "Number of rows to generate")
	seedCmd.Flags().BoolVarP(&seedYes, "yes", "y", false, "Automatically execute the generated SQL")
}

func runSeed(cmd *cobra.Command, args []string) error {
	connStr := ""
	if len(args) > 0 {
		connStr = args[0]
	} else {
		// Try defaults
		if _, err := os.Stat("recac.db"); err == nil {
			connStr = "recac.db"
		} else if _, err := os.Stat(".recac.db"); err == nil {
			connStr = ".recac.db"
		} else {
			return fmt.Errorf("connection string or file path required")
		}
	}

	// 1. Extract Schema
	fmt.Fprintf(cmd.OutOrStdout(), "🔍 analyzing schema for %s...\n", connStr)
	schema, err := extractSchema(connStr)
	if err != nil {
		return fmt.Errorf("failed to extract schema: %w", err)
	}

	if len(schema.Tables) == 0 {
		return fmt.Errorf("no tables found in database")
	}

	// 2. Select Table
	var targetTable *Table
	if seedTable != "" {
		for i, t := range schema.Tables {
			if strings.EqualFold(t.Name, seedTable) {
				targetTable = &schema.Tables[i]
				break
			}
		}
		if targetTable == nil {
			return fmt.Errorf("table '%s' not found", seedTable)
		}
	} else {
		var tableNames []string
		for _, t := range schema.Tables {
			tableNames = append(tableNames, t.Name)
		}
		var selected string
		err := askOneFunc(&survey.Select{
			Message: "Select table to seed:",
			Options: tableNames,
		}, &selected)
		if err != nil {
			return err
		}
		for i, t := range schema.Tables {
			if t.Name == selected {
				targetTable = &schema.Tables[i]
				break
			}
		}
	}

	// 3. Prepare Prompt
	dialect := "sqlite"
	if strings.HasPrefix(connStr, "postgres") {
		dialect = "postgres"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Table: %s\nColumns:\n", targetTable.Name))
	for _, c := range targetTable.Columns {
		pk := ""
		if c.PK {
			pk = " (PRIMARY KEY)"
		}
		fk := ""
		if c.FK {
			fk = " (FOREIGN KEY)"
		}
		sb.WriteString(fmt.Sprintf("- %s (%s)%s%s\n", c.Name, c.Type, pk, fk))
	}

	prompt := fmt.Sprintf(`You are a Database Seeding Assistant.
Generate %d SQL INSERT statements for the table '%s' (%s dialect).
Make the data realistic and varied.
Ensure types match (e.g. integers for IDs, valid emails, timestamps).

Schema:
%s

Requirements:
- Return ONLY the raw SQL.
- Do not wrap in code blocks.
- If a column is a primary key (auto-incrementing), omit it from INSERT if the dialect handles it automatically (e.g. SQLite INTEGER PRIMARY KEY, Postgres SERIAL). Otherwise, generate unique values.
- If a column is a Foreign Key, generate a placeholder value or a comment warning.
`, seedCount, targetTable.Name, dialect, sb.String())

	// 4. Generate SQL
	ctx := cmd.Context()
	cwd, _ := os.Getwd()
	provider := viper.GetString("provider")
	model := viper.GetString("model")

	ag, err := agentClientFactory(ctx, provider, model, cwd, "recac-seed")
	if err != nil {
		return fmt.Errorf("failed to create agent: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "🤖 Generating %d rows for '%s'...\n", seedCount, targetTable.Name)

	resp, err := ag.Send(ctx, prompt)
	if err != nil {
		return fmt.Errorf("agent failed: %w", err)
	}

	sqlQuery := utils.CleanCodeBlock(resp)

	// 5. Review & Execute
	if !seedYes {
		fmt.Fprintln(cmd.OutOrStdout(), "\nGenerated SQL:")
		fmt.Fprintln(cmd.OutOrStdout(), "------------------------------------------------")
		// Truncate preview if too long?
		previewLines := strings.Split(sqlQuery, "\n")
		if len(previewLines) > 10 {
			for i := 0; i < 10; i++ {
				fmt.Fprintln(cmd.OutOrStdout(), previewLines[i])
			}
			fmt.Fprintf(cmd.OutOrStdout(), "... and %d more lines\n", len(previewLines)-10)
		} else {
			fmt.Fprintln(cmd.OutOrStdout(), sqlQuery)
		}
		fmt.Fprintln(cmd.OutOrStdout(), "------------------------------------------------")

		confirm := false
		err := askOneFunc(&survey.Confirm{
			Message: "Execute this SQL?",
			Default: true,
		}, &confirm)
		if err != nil || !confirm {
			fmt.Fprintln(cmd.OutOrStdout(), "Cancelled.")
			return nil
		}
	}

	fmt.Fprintln(cmd.OutOrStdout(), "Executing SQL...")
	if err := execInsert(cmd.Context(), connStr, sqlQuery); err != nil {
		return fmt.Errorf("execution failed: %w", err)
	}

	fmt.Fprintln(cmd.OutOrStdout(), "✅ Seed complete!")
	return nil
}

func execInsert(ctx context.Context, connStr, query string) error {
	var dbType string
	var dsn string

	if strings.HasPrefix(connStr, "postgres://") || strings.HasPrefix(connStr, "postgresql://") {
		dbType = "postgres"
		dsn = connStr
	} else {
		dbType = "sqlite"
		dsn = connStr
	}

	db, err := sql.Open(dbType, dsn)
	if err != nil {
		return err
	}
	defer db.Close()

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	_, err = tx.ExecContext(ctx, query)
	if err != nil {
		tx.Rollback()
		return err
	}

	return tx.Commit()
}
