package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"recac/internal/utils"

	"github.com/charmbracelet/bubbles/list"
	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// tourCmd represents the tour command
var tourCmd = &cobra.Command{
	Use:   "tour",
	Short: "Take a guided tour of the codebase",
	Long:  `Explore the codebase with an interactive tour. The tour is generated by AI (if configured) or uses a default path to explain the key components of the project.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		p := tea.NewProgram(initialTourModel(), tea.WithAltScreen())
		if _, err := p.Run(); err != nil {
			return fmt.Errorf("error running tour: %w", err)
		}
		return nil
	},
}

func init() {
	rootCmd.AddCommand(tourCmd)
}

type TourStop struct {
	Name string `json:"title"`
	Path string `json:"path"`
	Desc string `json:"description"`
}

func (t TourStop) Title() string       { return t.Name }
func (t TourStop) Description() string { return t.Desc }
func (t TourStop) FilterValue() string { return t.Name }

type TourModel struct {
	list     list.Model
	viewport viewport.Model
	ready    bool
	width    int
	height   int
	err      error
	stops    []TourStop
	loading  bool
}

type TourLoadedMsg struct {
	stops []TourStop
	err   error
}

func initialTourModel() TourModel {
	l := list.New([]list.Item{}, list.NewDefaultDelegate(), 0, 0)
	l.Title = "Codebase Tour"
	l.SetShowHelp(false)

	return TourModel{
		list:    l,
		loading: true,
	}
}

func (m TourModel) Init() tea.Cmd {
	return loadTourCmd
}

func (m TourModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmd tea.Cmd
	var cmds []tea.Cmd

	switch msg := msg.(type) {
	case tea.KeyMsg:
		if msg.String() == "q" || msg.String() == "ctrl+c" {
			return m, tea.Quit
		}

	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height

		// Layout: 30% list, 70% viewport
		listWidth := int(float64(m.width) * 0.3)
		viewportWidth := m.width - listWidth - 4 // margins

		m.list.SetSize(listWidth, m.height-2)

		if !m.ready {
			m.viewport = viewport.New(viewportWidth, m.height-2)
			m.ready = true
		} else {
			m.viewport.Width = viewportWidth
			m.viewport.Height = m.height - 2
		}

		// Re-render content to fit new width if needed
		if m.list.Index() >= 0 && m.list.Index() < len(m.stops) {
			m.updateViewportContent(m.stops[m.list.Index()])
		}

	case TourLoadedMsg:
		m.loading = false
		m.stops = msg.stops

		if msg.err != nil {
			m.err = msg.err
		}

		items := make([]list.Item, len(m.stops))
		for i, s := range m.stops {
			items[i] = s
		}
		m.list.SetItems(items)

		// Select first item and load content
		if len(m.stops) > 0 {
			m.list.Select(0)
			m.updateViewportContent(m.stops[0])
		}

	case list.FilterMatchesMsg:
		// Handle filter matches if needed
	}

	// Update list
	var listCmd tea.Cmd
	oldIndex := m.list.Index()
	m.list, listCmd = m.list.Update(msg)
	cmds = append(cmds, listCmd)

	// If selection changed
	if m.list.Index() != oldIndex && m.list.Index() >= 0 && m.list.Index() < len(m.stops) {
		selectedStop := m.stops[m.list.Index()]
		m.updateViewportContent(selectedStop)
	}

	// Update viewport
	m.viewport, cmd = m.viewport.Update(msg)
	cmds = append(cmds, cmd)

	return m, tea.Batch(cmds...)
}

func (m *TourModel) updateViewportContent(stop TourStop) {
	content := fmt.Sprintf("# %s\n\n%s\n\n", stop.Name, stop.Desc)

	fileContent, err := os.ReadFile(stop.Path)
	if err == nil {
		content += fmt.Sprintf("## File: %s\n\n```\n%s\n```", stop.Path, string(fileContent))
	} else {
		// If it's a directory or invalid path, just show the description
		content += fmt.Sprintf("(File content not available: %v)", err)
	}

	m.viewport.SetContent(content)
}

var docStyle = lipgloss.NewStyle().Margin(1, 2)

func (m TourModel) View() string {
	if m.loading {
		return "Loading tour... (Checking AI configuration...)"
	}
	// Show error but still render UI if we have stops
	errorMsg := ""
	if m.err != nil {
		errorMsg = fmt.Sprintf("Warning: %v\nUsing fallback tour.\n\n", m.err)
	}

	if !m.ready {
		return "Initializing..."
	}

	return docStyle.Render(lipgloss.JoinHorizontal(
		lipgloss.Top,
		m.list.View(),
		strings.Repeat(" ", 4),
		lipgloss.JoinVertical(lipgloss.Top, errorMsg, m.viewport.View()),
	))
}

func loadTourCmd() tea.Msg {
	// 1. Check if AI is configured
	provider := viper.GetString("provider")
	model := viper.GetString("model")

	// Default fallback
	fallbackStops := []TourStop{
		{Name: "README.md", Path: "README.md", Desc: "Project overview and documentation."},
		{Name: "Main Entry Point", Path: "cmd/recac/main.go", Desc: "The CLI entry point."},
		{Name: "Internal Logic", Path: "internal/", Desc: "Core business logic."},
		{Name: "Configuration", Path: "config.yaml", Desc: "Project configuration file."},
	}

	if provider == "" || model == "" {
		return TourLoadedMsg{stops: fallbackStops, err: fmt.Errorf("AI provider not configured")}
	}

	// 2. Generate Context
	ctxOpts := ContextOptions{
		Roots: []string{"."},
		Tree: true,
		MaxSize: 50 * 1024, // Limit context size
		Ignore: []string{"go.sum", "test_output.txt"},
	}
	contextStr, err := GenerateCodebaseContext(ctxOpts)
	if err != nil {
		 // Fallback on error
		 return TourLoadedMsg{stops: fallbackStops, err: fmt.Errorf("failed to generate context: %w", err)}
	}

	// 3. Call AI
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	agent, err := agentClientFactory(ctx, provider, model, ".", "recac-tour")
	if err != nil {
		return TourLoadedMsg{stops: fallbackStops, err: fmt.Errorf("failed to create agent: %w", err)}
	}

	prompt := fmt.Sprintf(`Analyze the following file tree and file contents. Identify the top 5-10 most critical files or directories that a new developer must understand to grasp the architecture of this project. For each, provide a 'title', the 'path', and a concise 'description' (2-3 sentences) explaining its purpose.

	Return the result strictly as a JSON list of objects. Example:
	[
		{"title": "Main", "path": "main.go", "description": "Entry point"},
		{"title": "Models", "path": "pkg/models", "description": "Data structures"}
	]

	Codebase Context:
	%s
	`, contextStr)

	response, err := agent.Send(ctx, prompt)
	if err != nil {
		 return TourLoadedMsg{stops: fallbackStops, err: fmt.Errorf("agent failed: %w", err)}
	}

	// 4. Parse JSON
	jsonStr := utils.CleanJSONBlock(response)
	var stops []TourStop
	if err := json.Unmarshal([]byte(jsonStr), &stops); err != nil {
		// Fallback if parsing fails
		return TourLoadedMsg{stops: fallbackStops, err: fmt.Errorf("failed to parse AI response: %w", err)}
	}

	if len(stops) == 0 {
		return TourLoadedMsg{stops: fallbackStops}
	}

	return TourLoadedMsg{stops: stops}
}
