package main

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"recac/internal/utils"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	workflowAutoApprove bool
)

// WorkflowPlan represents the structure of the AI-generated workflow
type WorkflowPlan struct {
	Title string         `json:"title"`
	Steps []WorkflowStep `json:"steps"`
}

// WorkflowStep represents a single step in the workflow
type WorkflowStep struct {
	Command     string `json:"command"`
	Description string `json:"description"`
}

var workflowCmd = &cobra.Command{
	Use:   "workflow [goal]",
	Short: "Execute a multi-step workflow generated by AI",
	Long: `Translates a high-level goal into a sequence of shell commands (a workflow) using AI.
It plans the steps, confirms them with you, and then executes them in order.

Example:
  recac workflow "setup a new git repo, create a README, and commit it"
`,
	Args: cobra.MinimumNArgs(1),
	RunE: runWorkflowCmd,
}

func init() {
	rootCmd.AddCommand(workflowCmd)
	workflowCmd.Flags().BoolVarP(&workflowAutoApprove, "yes", "y", false, "Automatically execute the plan without confirmation")
}

func runWorkflowCmd(cmd *cobra.Command, args []string) error {
	goal := strings.Join(args, " ")
	ctx := context.Background()
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get current working directory: %w", err)
	}

	provider := viper.GetString("provider")
	model := viper.GetString("model")

	// 1. Get Agent
	ag, err := agentClientFactory(ctx, provider, model, cwd, "recac-workflow")
	if err != nil {
		return fmt.Errorf("failed to create agent: %w", err)
	}

	// 2. Construct Prompt
	prompt := fmt.Sprintf(`You are a DevOps Automation Expert.
Your goal is to generate a sequence of shell commands to achieve the following objective:
"%s"

Requirements:
- Use standard shell commands (git, echo, curl, etc.) or 'recac' subcommands.
- Ensure the steps are logical and sequential.
- Return the result as a raw JSON object with the following structure:
{
  "title": "Short title of the workflow",
  "steps": [
    { "command": "command to execute", "description": "Short explanation" },
    { "command": "next command", "description": "..." }
  ]
}

Do not wrap the JSON in markdown code blocks. Just return the raw JSON string.
`, goal)

	fmt.Fprintln(cmd.OutOrStdout(), "🤖 Generating workflow plan...")

	resp, err := ag.Send(ctx, prompt)
	if err != nil {
		return fmt.Errorf("agent failed: %w", err)
	}

	// 3. Parse Response
	jsonStr := utils.CleanJSONBlock(resp)
	var plan WorkflowPlan
	if err := json.Unmarshal([]byte(jsonStr), &plan); err != nil {
		return fmt.Errorf("failed to parse agent response: %w\nResponse: %s", err, resp)
	}

	if len(plan.Steps) == 0 {
		fmt.Fprintln(cmd.OutOrStdout(), "Agent returned no steps.")
		return nil
	}

	// 4. Display Plan
	fmt.Fprintf(cmd.OutOrStdout(), "\n📋 Plan: %s\n", plan.Title)
	for i, step := range plan.Steps {
		fmt.Fprintf(cmd.OutOrStdout(), "%d. %s\n   (Cmd: %s)\n", i+1, step.Description, step.Command)
	}
	fmt.Fprintln(cmd.OutOrStdout(), "")

	// 5. Confirm
	if !workflowAutoApprove {
		fmt.Fprint(cmd.OutOrStdout(), "Execute this workflow? [y/N]: ")
		reader := bufio.NewReader(cmd.InOrStdin())
		input, _ := reader.ReadString('\n')
		input = strings.TrimSpace(strings.ToLower(input))
		if input != "y" && input != "yes" {
			fmt.Fprintln(cmd.OutOrStdout(), "Aborted.")
			return nil
		}
	}

	// 6. Execute
	fmt.Fprintln(cmd.OutOrStdout(), "\n🚀 Executing...")
	for i, step := range plan.Steps {
		fmt.Fprintf(cmd.OutOrStdout(), "[%d/%d] %s...\n", i+1, len(plan.Steps), step.Description)

		// Use sh -c to allow complex commands (pipes, etc)
		c := execCommand("sh", "-c", step.Command)
		c.Stdout = cmd.OutOrStdout()
		c.Stderr = cmd.ErrOrStderr()

		if err := c.Run(); err != nil {
			// Stop on error
			return fmt.Errorf("step %d failed: %w", i+1, err)
		}
	}

	fmt.Fprintln(cmd.OutOrStdout(), "✅ Workflow completed successfully.")
	return nil
}
