package orchestrator

import (
	"bytes"
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

func TestAPIMatrixSubmission(t *testing.T) {
	mockPoller := new(MockPoller)
	mockSpawner := new(MockSpawner)
	logger := slog.Default()

	// Initial poll mock
	mockPoller.On("Poll", mock.Anything, mock.Anything).Return([]WorkItem{}, nil).Maybe()

	orch := New(mockPoller, mockSpawner, 1*time.Minute)

	mux := http.NewServeMux()
	RegisterAPI(mux, orch, logger, context.Background())
	server := httptest.NewServer(mux)
	defer server.Close()

	t.Run("Valid Matrix Submission", func(t *testing.T) {
		reqBody := map[string]interface{}{
			"base_item": map[string]interface{}{
				"id":       "matrix-base",
				"summary":  "Test Matrix",
				"repo_url": "https://example.com/repo",
				"env_vars": map[string]string{
					"GLOBAL_VAR": "global_value",
				},
			},
			"matrix": map[string][]string{
				"OS": {"linux", "windows"},
				"GO": {"1.20", "1.21"},
			},
		}

		payload, _ := json.Marshal(reqBody)

		// Since we use background mock spawning in processWorkItemInternal, we don't assert mockSpawner strictly if it races.
		// Instead, we can just assert that SubmitJob succeeded and the jobs are in activeJobs.
		// Let's add mockSpawner expectations for the active ones.
		mockSpawner.On("Spawn", mock.Anything, mock.MatchedBy(func(item WorkItem) bool {
			return item.ID == "matrix-base-1" || item.ID == "matrix-base-2" || item.ID == "matrix-base-3" || item.ID == "matrix-base-4"
		})).Return(nil).Maybe()

		resp, err := http.Post(server.URL+"/jobs/matrix", "application/json", bytes.NewBuffer(payload))
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusAccepted, resp.StatusCode)

		var result map[string]interface{}
		err = json.NewDecoder(resp.Body).Decode(&result)
		assert.NoError(t, err)

		submitted := result["submitted"].([]interface{})
		assert.Len(t, submitted, 4)
		errors := result["errors"]
		if errors != nil {
			errList := errors.([]interface{})
			assert.Len(t, errList, 0)
		}

		// Verify that active jobs exist and have correct generated names and combined env vars
		// Give it a little more time to ensure the background spawns have populated the active jobs map fully
		assert.Eventually(t, func() bool {
			// Since background jobs might complete instantly or stay active depending on mock, we should check GetCompletedJobs or GetActiveJobs
			jobs := append(orch.GetActiveJobs(), orch.GetCompletedJobs()...)
			if len(jobs) != 4 {
				return false
			}

			foundJob1 := false
			foundJob2 := false

			for _, job := range jobs {
				if job.WorkItem.EnvVars["GO"] == "1.20" && job.WorkItem.EnvVars["OS"] == "linux" {
					foundJob1 = true
				}
				if job.WorkItem.EnvVars["GO"] == "1.21" && job.WorkItem.EnvVars["OS"] == "windows" {
					foundJob2 = true
				}
			}

			return foundJob1 && foundJob2
		}, 5*time.Second, 100*time.Millisecond, "Should find jobs correctly generated by matrix")
	})

	t.Run("Empty Matrix", func(t *testing.T) {
		reqBody := map[string]interface{}{
			"base_item": map[string]interface{}{
				"id":       "matrix-base-empty",
				"summary":  "Test Matrix Empty",
				"repo_url": "https://example.com/repo",
			},
			"matrix": map[string][]string{},
		}

		payload, _ := json.Marshal(reqBody)

		mockSpawner.On("Spawn", mock.Anything, mock.MatchedBy(func(item WorkItem) bool {
			return item.ID == "matrix-base-empty"
		})).Return(nil).Maybe()

		resp, err := http.Post(server.URL+"/jobs/matrix", "application/json", bytes.NewBuffer(payload))
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusAccepted, resp.StatusCode)

		var result map[string]interface{}
		json.NewDecoder(resp.Body).Decode(&result)
		submitted := result["submitted"].([]interface{})
		assert.Len(t, submitted, 1)
		assert.Equal(t, "matrix-base-empty", submitted[0])
	})

	t.Run("Missing Base ID", func(t *testing.T) {
		reqBody := map[string]interface{}{
			"base_item": map[string]interface{}{
				"summary": "No ID",
			},
		}

		payload, _ := json.Marshal(reqBody)

		resp, err := http.Post(server.URL+"/jobs/matrix", "application/json", bytes.NewBuffer(payload))
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	})

	// Wait a moment for spawns to trigger
	time.Sleep(100 * time.Millisecond)

	mockSpawner.AssertExpectations(t)
}
