package orchestrator

import (
	"context"
	"io/ioutil"
	"log/slog"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCronPoller(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(ioutil.Discard, nil))
	ctx := context.Background()

	// Create a temporary template file
	dir := t.TempDir()
	templatePath := filepath.Join(dir, "template.json")
	templateContent := `{
		"summary": "Cron Job Task",
		"description": "This is generated by a cron schedule",
		"repo_url": "https://github.com/example/repo"
	}`
	err := os.WriteFile(templatePath, []byte(templateContent), 0644)
	require.NoError(t, err)

	t.Run("Invalid Schedule", func(t *testing.T) {
		_, err := NewCronPoller("invalid cron", templatePath)
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "invalid cron schedule")
	})

	t.Run("Invalid Template Path", func(t *testing.T) {
		_, err := NewCronPoller("* * * * *", "nonexistent.json")
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "failed to load cron template")
	})

	t.Run("Valid Schedule - Future Run", func(t *testing.T) {
		// Schedule for next year to ensure it's in the future
		poller, err := NewCronPoller("0 0 1 1 *", templatePath)
		require.NoError(t, err)

		items, err := poller.Poll(ctx, logger)
		assert.NoError(t, err)
		assert.Empty(t, items, "Should not return items before scheduled time")
	})

	t.Run("Valid Schedule - Due Run", func(t *testing.T) {
		poller, err := NewCronPoller("* * * * *", templatePath)
		require.NoError(t, err)

		// Manually set nextRun to the past to simulate time passing
		poller.nextRun = time.Now().Add(-1 * time.Minute)

		items, err := poller.Poll(ctx, logger)
		assert.NoError(t, err)
		assert.Len(t, items, 1, "Should return 1 item when due")

		item := items[0]
		assert.Contains(t, item.ID, "cron-")
		assert.Equal(t, "Cron Job Task", item.Summary)
		assert.Equal(t, "This is generated by a cron schedule", item.Description)
		assert.Equal(t, "https://github.com/example/repo", item.RepoURL)

		// Verify next run is now in the future
		assert.True(t, poller.nextRun.After(time.Now()))

		// Poll again immediately, should be empty
		items2, err := poller.Poll(ctx, logger)
		assert.NoError(t, err)
		assert.Empty(t, items2, "Should not return items immediately after a run")
	})

	t.Run("Ping and UpdateStatus", func(t *testing.T) {
		poller, err := NewCronPoller("* * * * *", templatePath)
		require.NoError(t, err)

		err = poller.Ping(ctx)
		assert.NoError(t, err)

		err = poller.UpdateStatus(ctx, WorkItem{}, "Done", "test")
		assert.NoError(t, err)
	})

	t.Run("Reloads Template", func(t *testing.T) {
		poller, err := NewCronPoller("* * * * *", templatePath)
		require.NoError(t, err)

		// Manually set nextRun to the past
		poller.nextRun = time.Now().Add(-1 * time.Minute)

		// Modify template file
		newContent := `{
			"summary": "Updated Task",
			"description": "Updated description"
		}`
		err = os.WriteFile(templatePath, []byte(newContent), 0644)
		require.NoError(t, err)

		items, err := poller.Poll(ctx, logger)
		assert.NoError(t, err)
		assert.Len(t, items, 1)
		assert.Equal(t, "Updated Task", items[0].Summary)
	})
}
