# Service Account for Recac Orchestrator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recac-orchestrator-sa
  namespace: default
  labels:
    app: recac-orchestrator
---
# Role for the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: recac-orchestrator-role
  namespace: default
  labels:
    app: recac-orchestrator
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# RoleBinding to bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recac-orchestrator-rolebinding
  namespace: default
  labels:
    app: recac-orchestrator
subjects:
- kind: ServiceAccount
  name: recac-orchestrator-sa
  namespace: default
roleRef:
  kind: Role
  name: recac-orchestrator-role
  apiGroup: rbac.authorization.k8s.io
