package agent

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// MockAgent is a simple mock agent for testing and mock mode
// It returns predefined responses without making actual API calls
type MockAgent struct {
	responsePrefix string
	forcedResponse string
}

// NewMockAgent creates a new mock agent
func NewMockAgent() *MockAgent {
	return &MockAgent{
		responsePrefix: "Mock agent response",
	}
}

// SetResponse forces a specific response from the agent
func (m *MockAgent) SetResponse(response string) {
	m.forcedResponse = response
}

// Send implements the Agent interface
// It returns a mock response that acknowledges the prompt
func (m *MockAgent) Send(ctx context.Context, prompt string) (string, error) {
	if m.forcedResponse != "" {
		return m.forcedResponse, nil
	}

	// Heuristic 1: Check for "Technical Program Manager" prompt (Planning Phase)
	if strings.Contains(prompt, "Technical Program Manager") {
		return `[
  {
    "id": "mock-task-1",
    "title": "Mock Task 1",
    "description": "This is a mock task generated by the mock agent.",
    "type": "task",
    "status": "todo",
    "dependencies": []
  }
]`, nil
	}

	// Heuristic 2: Check for execution phase (e.g. "status": "pending")
	if strings.Contains(prompt, "\"status\": \"pending\"") || strings.Contains(prompt, `"status": "pending"`) {
		return fmt.Sprintf(`Plan: Execute mock command.
Command: echo "Mock command executed" && echo "Success: Mock command executed"
`), nil
	}

	// Heuristic 3: Check for PRIMES task
	if strings.Contains(prompt, "ID:[PRIMES]") || strings.Contains(prompt, "Implement prime calculation logic") {
		return `Plan: Create primes.py script.
Command: cat <<EOF > primes.py
def is_prime(n):
    if n <= 1: return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0: return False
    return True

primes = [i for i in range(1, 101) if is_prime(i)]
import json
with open('primes.json', 'w') as f:
    json.dump(primes, f)
EOF
python3 primes.py
git config user.email "you@example.com" || true
git config user.name "Your Name" || true
git add primes.py primes.json || true
git commit -m "Add primes implementation" || echo "Nothing to commit"
echo "Success: Mock command executed"
`, nil
	}

	// Default response
	response := fmt.Sprintf("%s:\n\nI received your prompt (%d characters). In mock mode, I would process this request and provide a response. The actual implementation would call the AI provider API here.\n\nPrompt preview: %s...",
		m.responsePrefix, len(prompt), truncateString(prompt, 100))
	return response, nil
}

// SendStream implements the Agent interface
func (m *MockAgent) SendStream(ctx context.Context, prompt string, onChunk func(string)) (string, error) {
	// Simulate streaming delay
	time.Sleep(10 * time.Millisecond)
	resp, err := m.Send(ctx, prompt)
	if err == nil && onChunk != nil {
		onChunk(resp)
	}
	return resp, err
}

// truncateString truncates a string to a maximum length
func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}
