package agent

import (
	"context"
	"fmt"
	"strings"
)

// MockAgent is a simple mock agent for testing and mock mode
// It returns predefined responses without making actual API calls
type MockAgent struct {
	responsePrefix string
	forcedResponse string
}

// NewMockAgent creates a new mock agent
func NewMockAgent() *MockAgent {
	return &MockAgent{
		responsePrefix: "Mock agent response",
	}
}

// SetResponse forces a specific response from the agent
func (m *MockAgent) SetResponse(response string) {
	m.forcedResponse = response
}

// Send implements the Agent interface
// It returns a mock response that acknowledges the prompt
func (m *MockAgent) Send(ctx context.Context, prompt string) (string, error) {
	if m.forcedResponse != "" {
		return m.forcedResponse, nil
	}

	// Heuristic: If prompt asks for JSON ticket plan (TPM role), return valid JSON
	if strings.Contains(prompt, "Technical Program Manager") && strings.Contains(prompt, "JSON") {
		return `{
  "id": "PRIMES",
  "project_name": "prime-python",
  "tickets": [
    {
      "title": "Implement Prime Number Generator",
      "description": "Create a Python script to generate prime numbers.",
      "type": "Task",
      "status": "Todo",
      "id": "PRIMES-1",
      "dependencies": []
    }
  ]
}`, nil
	}

	// Heuristic: If prompt asks for implementation (primes.py), return code
	// We check for the ticket title generated by the Mock TPM above.
	if strings.Contains(prompt, "primes.py") || strings.Contains(prompt, "Calculate primes") || strings.Contains(prompt, "Implement Prime Number Generator") {
		return `I will implement the prime number generator in Python.

` + "```bash" + `
cat << 'EOF' > primes.py
def is_prime(n):
    """Checks if a number is a prime number."""
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        n = int(sys.argv[1])
        print(is_prime(n))
EOF
` + "```" + `

I have created the primes.py file.
`, nil
	}

	// Heuristic: If prompt is for QA or verification
	if strings.Contains(prompt, "QA") || strings.Contains(prompt, "Review") || strings.Contains(prompt, "verify") {
		return `I have verified the implementation. It looks correct.

` + "```bash" + `
python3 primes.py 7
` + "```" + `
`, nil
	}

	// Return a mock response that shows the agent received the prompt
	// This allows the session to run without requiring real API keys
	response := fmt.Sprintf("%s:\n\nI received your prompt (%d characters). In mock mode, I would process this request and provide a response. The actual implementation would call the AI provider API here.\n\nPrompt preview: %s...",
		m.responsePrefix, len(prompt), truncateString(prompt, 100))
	return response, nil
}

// SendStream implements the Agent interface
func (m *MockAgent) SendStream(ctx context.Context, prompt string, onChunk func(string)) (string, error) {
	resp, err := m.Send(ctx, prompt)
	if err == nil && onChunk != nil {
		onChunk(resp)
	}
	return resp, err
}

// truncateString truncates a string to a maximum length
func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}
