package agent

import (
	"context"
	"fmt"
	"strings"
)

// MockAgent is a simple mock agent for testing and mock mode
// It returns predefined responses without making actual API calls
type MockAgent struct {
	responsePrefix string
	forcedResponse string
}

// NewMockAgent creates a new mock agent
func NewMockAgent() *MockAgent {
	return &MockAgent{
		responsePrefix: "Mock agent response",
	}
}

// SetResponse forces a specific response from the agent
func (m *MockAgent) SetResponse(response string) {
	m.forcedResponse = response
}

// Send implements the Agent interface
// It returns a mock response that acknowledges the prompt
func (m *MockAgent) Send(ctx context.Context, prompt string) (string, error) {
	if m.forcedResponse != "" {
		return m.forcedResponse, nil
	}

	// Detect Planner Request (recac plan)
	if isPlannerPrompt(prompt) {
		return `{
  "project_name": "Mock Project",
  "features": [
    {
      "id": "req-mock-1",
      "title": "Mock Feature 1",
      "description": "This is a mock feature generated by the mock agent.",
      "priority": "High",
      "complexity": "Low",
      "status": "pending"
    }
  ]
}`, nil
	}

	// Return a mock response that shows the agent received the prompt
	// This allows the session to run without requiring real API keys
	response := fmt.Sprintf("%s:\n\nI received your prompt (%d characters). In mock mode, I would process this request and provide a response. The actual implementation would call the AI provider API here.\n\nPrompt preview: %s...",
		m.responsePrefix, len(prompt), truncateString(prompt, 100))
	return response, nil
}

func isPlannerPrompt(prompt string) bool {
	// Simple keyword detection for the planner prompt
	// "You are an expert Technical Program Manager" is the start of prompts.TPMAgent / Planner?
	// Actually prompts.Planner usually has "feature_list.json" or "JSON" instructions.
	// But let's check for keywords often found in the Planner prompt.
	// The prompt template is likely 'planner.md'.
	// A safe bet is checking if it asks for a JSON list of features.
	return (contains(prompt, "Technical Program Manager") || contains(prompt, "Planner")) &&
		(contains(prompt, "JSON") || contains(prompt, "feature_list"))
}

func contains(s, substr string) bool {
	return strings.Contains(s, substr)
}

// SendStream implements the Agent interface
func (m *MockAgent) SendStream(ctx context.Context, prompt string, onChunk func(string)) (string, error) {
	resp, err := m.Send(ctx, prompt)
	if err == nil && onChunk != nil {
		onChunk(resp)
	}
	return resp, err
}

// truncateString truncates a string to a maximum length
func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}
